#!/usr/bin/env bash
#
# appmakefile.sh -- write the Makefile that rebuilds one application, on WOS.
#
#   tools/appmakefile.sh <name> <sourcecode-directory>
#
# The result goes on standard output and the build installs it beside the
# sources, so every /app/<name>/sourcecode holds the Makefile for that
# application.  Generated rather than written, and generated at every build,
# because fifty-four hand-written Makefiles are fifty-four chances for one of
# them to say something different from the rest.  Editing one on the machine is
# fine and normal; the next build writes it again.
#
# Two things it has to work out for itself, which is the whole reason this is a
# program and not a template:
#
#   * the objects, one per .c file in the directory;
#   * a rule per object, since the make on WOS has no pattern rules -- it is a
#     subset, and generating the repetition is cheaper than implementing `%`.
#
# Header dependencies are every .h in the same directory rather than the ones
# each file actually includes.  An application here is a handful of files that
# all know about each other; the cost of being imprecise is recompiling three
# files instead of two, and the cost of being precise is a dependency scanner
# that has to understand the preprocessor.
#
set -uo pipefail

name=${1:?usage: appmakefile.sh <name> <sourcecode-directory>}
dir=${2:?usage: appmakefile.sh <name> <sourcecode-directory>}

sources=$(cd "$dir" && ls *.c 2>/dev/null | sort)
headers=$(cd "$dir" && ls *.h 2>/dev/null | sort | tr '\n' ' ')
objects=$(echo "$sources" | sed 's/\.c$/.o/' | tr '\n' ' ')

# Trim the trailing spaces `tr` leaves behind, so the generated file has no
# whitespace nobody typed.
headers=${headers% }
objects=${objects% }

cat <<EOF
# $name -- rebuilt on the machine it runs on.
#
# Generated by the build (tools/appmakefile.sh), so this file and the fifty-three
# beside it say the same thing.  Edit it if you like: it is a file on a disk
# like any other, and the next build writes it again.
#
#   make            rebuild /app/$name/launch if a source file is newer
#   make clean      remove the objects
#   make -n         print the commands without running them
#
# The compiler is wcc, which is on this machine like everything else -- its own
# source is in /app/wcc/sourcecode.  Another one can be tried without editing
# this file: \`make CC=something\`.

NAME    = $name
CC      = wcc

# Where the headers and the library the build installed live.  /include holds
# wkernel.h and the hosted C library's headers; /lib holds what to link
# against and the linker script that says where a program is loaded.
CFLAGS  = -c -I/include
LDFLAGS = -T /lib/user.ld
LIBS    = /lib/libc.a /lib/libwkernel.a

OBJ     = $objects
EOF

if [ -n "$headers" ]; then
    echo "HEADERS = $headers"
fi

cat <<EOF

/app/\$(NAME)/launch: \$(OBJ)
	\$(CC) \$(LDFLAGS) -o \$@ \$(OBJ) \$(LIBS)

EOF

for src in $sources; do
    obj=${src%.c}.o
    if [ -n "$headers" ]; then
        echo "$obj: $src \$(HEADERS)"
    else
        echo "$obj: $src"
    fi
    printf '\t$(CC) $(CFLAGS) -o $@ %s\n\n' "$src"
done

cat <<EOF
clean:
	rm -f \$(OBJ)

.PHONY: clean
EOF
